name: GoKart

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    env:
      source-directory: 'src/'

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Security Scan
      uses: kitabisa/gokart-action@v1.0.0
      with:
        globalsTainted: false
        directory: ${{ env.source-directory }}
        output: results.txt
