# https://horusec.io/docs/cli/installation/#installation-via-pipeline
# does not output SARIF, only console output

name: Horusec

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Security Scan
      # specify -e="false" or remove the parameter from the command below to avoid failing the scan
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
        horusec start -p="src" -e="true"
