# https://semgrep.dev/docs/semgrep-ci/overview/

name: Semgrep

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    if: (github.actor != 'dependabot[bot]')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Security Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
        generateSarif: "1"
        # to connect with the application
        # publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
        # publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        # comment/uncomment to avoid failing the scan on pushes
        # auditOn: push
        # env:
          # SEMGREP_TIMEOUT: 300

    - name: Upload SARIF File
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: semgrep.sarif
      if: always()
