# https://semgrep.dev/docs/semgrep-ci/overview/

name: SonarCloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Security Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >-
          -Dsonar.organization=ivan-sincek
          -Dsonar.projectKey=ivan-sincek_go-actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # this token is commented on purpose to check if there will be any alerts
        # SONAR_TOKEN: 0662aa487c888477fe19224952dd67f7689b1ad7
