name: Test Go Application

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      source-directory: 'src/'

    strategy:
      matrix:
        go-version: [ 1.18 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      working-directory: ${{ env.source-directory }}
      run: go build -v ./

    - name: Run Tests
      working-directory: ${{ env.source-directory }}
      run: go test -v ./
